### ISSUE TITLE
在macOS环境下默认路径错误

### ISSUE THREAD

**Issue by SEmmmer** [covscript/covscript-intellij#45]
你好，在我安装macOS的Covscript，并且尝试配置IDEA的插件时出现了以下问题：

1. 插件的cs文件引导**默认**为
`/usr/bin/cs`
而在macOS上，其**本应该**是
`/Applications/CovScript.app/Contents/MacOS/covscript/bin/cs`

2. 在步骤 Add Configuration 时：
选项 `Working directory` 为空
选项 `import path` 为空

望解决。

**Comment by ice1000** [comment]
Add Configuration 一般不会被用到，推荐的用法是打开一个文件后右键执行，这样会直接根据当前文件创建一个 run configuration。前一个问题 —— 我早就想知道 macos 的默认路径了，谢谢提醒。

**Comment by ice1000** [comment]
为啥 close 了？解释下呗

**Comment by SEmmmer** [comment]
不是问题都了解了么，就等版本更新了
